version: '3.5'

services:
  npm:
    build:
      context: '.'
      target: npm

  composer:
    build:
      context: '.'
      target: composer

  laravel-app:
    build:
      context: '.'
      target: laravel
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      - DB_HOST=mysql-db
    ports:
      - 8000:80

  mysql-db:
    image: mysql:5.7
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}